USE DEMO_DB;
USE SCHEMA DATA_GOV_METADATA_APP;

--DROP SEQUENCE

DROP SEQUENCE IF EXISTS GE_FUNCTION_RULE_MAP_SEQ; 

DROP SEQUENCE IF EXISTS DQ_VIOLATIONS_SEQ;

DROP SEQUENCE IF EXISTS DQ_RULES_SEQ;

DROP SEQUENCE IF EXISTS PROCESS_METADATA_SEQ;

--DROP TABLES

DROP TABLE IF EXISTS DATASETS;

DROP TABLE IF EXISTS ATTRIBUTES ;

DROP TABLE IF EXISTS DQ_RULES;

DROP TABLE IF EXISTS GE_FUNCTION_RULE_MAP;

DROP TABLE IF EXISTS DQ_VIOLATIONS;

DROP TABLE IF EXISTS SENSITIVE_ATTRIBUTES;

DROP TABLE IF EXISTS PROCESS_METADATA;

--DROP PROCEDURES

DROP PROCEDURE IF EXISTS create_metadata(VARCHAR,VARCHAR,VARCHAR);

DROP PROCEDURE IF EXISTS create_dq_rule(VARCHAR,VARCHAR,VARCHAR);

DROP PROCEDURE IF EXISTS rundq_rules(VARCHAR,VARCHAR,VARCHAR);

DROP PROCEDURE IF EXISTS collect_processmetadata(VARCHAR,VARCHAR,VARCHAR);


